name: api_explorer
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  code_editor: ^1.3.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive_flutter: ^1.1.0
  http:
  intl: ^0.17.0
  bitsdojo_window: ^0.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"

  
flutter_icons:
  image_path: "assets/images/app-icon.png"
  android: "ic_launcher"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/app-adaptive.png"
  ios: true

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
